class FatalError(Exception):
    pass


class AuthError(FatalError):
    pass
